/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_sqrlauth_enscrypt_Enscrypt */

#ifndef _Included_com_sqrlauth_enscrypt_Enscrypt
#define _Included_com_sqrlauth_enscrypt_Enscrypt
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_sqrlauth_enscrypt_Enscrypt
 * Method:    enscrypt_ms
 * Signature: ([BLjava/lang/String;[BI)I
 */
JNIEXPORT jint JNICALL Java_com_sqrlauth_enscrypt_Enscrypt_enscrypt_1ms
  (JNIEnv *, jobject, jbyteArray, jstring, jbyteArray, jint);

/*
 * Class:     com_sqrlauth_enscrypt_Enscrypt
 * Method:    enscrypt
 * Signature: ([BLjava/lang/String;[BI)I
 */
JNIEXPORT jint JNICALL Java_com_sqrlauth_enscrypt_Enscrypt_enscrypt
  (JNIEnv *, jobject, jbyteArray, jstring, jbyteArray, jint);

/*
 * Class:     com_sqrlauth_enscrypt_Enscrypt
 * Method:    get_real_time
 * Signature: ()D
 */
JNIEXPORT jdouble JNICALL Java_com_sqrlauth_enscrypt_Enscrypt_get_1real_1time
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
